services:
  app:
    image: ghcr.io/ianfebi01/gendut-grosir-be:${IMAGE_TAG:-latest}
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      - mongodb
    networks:
      - proxy
      - backend

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data_3:/data/db
    networks:
      - backend

volumes:
  mongo_data_3:

networks:
  proxy:
    external: true
  backend:
