version: '3.7'
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ianfebi01
      - MONGO_INITDB_ROOT_PASSWORD=huhuhaha
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  gendut-grosir-be:
    restart: always
    build: .
    container_name: gendut-grosir-be
    # image: gendut-grosir-be
    ports:
      - 8001:8000
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - app
  # gendut-grosir-fe:
  #   restart: always
  #   build : ./gendut-grosir
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - app
networks:
  app:
    driver: bridge
volumes:
  db: